### ISSUE TITLE
Arabskie znaczki i odwrócenie listy

### ISSUE THREAD

**Issue by KrzysztofZawisla** [losek1/Sounder#3]
Jak mam piosenki z arabskimi znaczkami to odwraca listę.

**Comment by losek1** [comment]
t̖̦̟̹̼̬͓̳̟̣͎̹͍̺̱̠̜̮͋ͧ͛̃̍͆͊̑͑̌͑ͦ̅́͘͝o̧̳̳͙͉̠͍͇͈̰̩̻͈̣̬̟̟ͩͤ̽͋ͤ͑́ͅͅ ̴̴̧͎̣̗̣̩̥͚̬̗̙͉͈̖͈͚̩͖ͣͣ̾͒̈̄́̿ͤ̐͛͆̆ͥ̚͢ṅ͍̙̥͔͉͔̼̘͉̝͈͕̳̂̈̾ͭ̉͊͊̎̌̐͌ͦ̐̒̕͡ͅí̴̛͔̮̜̙͙ͤ̓̿̊͊ͯ̓ͪ̑̓ͣ͜͡e͋̀̒̑ͬ͊҉̡̱̫̜̙̲̖̤̪͖̟̲͔̜͙ ̸̗̺̭̺̝̲̬̞͎̩̭͓̲̓͛ͧ̒̂̽ͬ̍̑̍͆̉͛ͥͅͅs̡̨̞̻͈̥̠̤͓̲͕̻̼̟͇̮̩̱̫̻̓́͐ͧͧ̆ͩ͊̊̓̕͘ł̨͓͙̠̹̗̤̝̲̻̱͙̖̗̩̙̺͍͓̏̑͗̇ͫ͑̽͌ͪ̚͡ͅu̧̢̝̦̫̫̳̭͙͔̫̩̦̙͎̰͚̞̥͒͌͂ͭ̉̾ͬ̒̃̓̓̇̍͗̏ͥ̀́͠c̭̖̗̮̘̖̼̯̟͍̗̽ͣ̏͌̀̕͢ͅh̨ͮͭ͆̾͛̍ͣ̐̆̎̄̒̾͆̊͐̇͞҉͎̬̖̭̤̝̯͈̳̳͖̙̦a̢̡̛͔͎̬̮̭͎̖̫ͧ̔͗̑ͧ͋̕j̢̡̨̯̮͙̬̺͇̣̣̺̣̺̺̲͉̦͗ͣͥ̌̎̂͒͑͑̄̽ͬ̿̾̋͐̕ ̷̺̲͉̻̟̹͉̙̦̦͈͖̼̲̟̟͗ͧͮͯ̀͑ͪ̎̿̏͛͒ͥ̎̃̎̚̕ͅņ̴͔̻͔̱͕̦̱̘̲̱͓͇̲̘̮͔̟̆̐ͣͨ̓͘i̷̼͔̼͖̲̩̓̑͑̉̔̑̌ͮ̓ͭ͐̆ͬ͊̒́̕c̶̜̤̳̳̻̓͌ͮͥ̄ͬ̀͜ ̡̐͂͒̃ͦ҉̹̫̤͓̖͙͔͍͝z̵̻̹̠̰̖̞̜̝̋̾ͣ͛ͧͩ̉̿̒̉͞͠͞ ̸͉̲̩̪̞̣̣̟̬͎̩̝̞͍͖͕̏͂̄̐̀͜͡z̧̨̟͇̤̻̰̉ͯ͂͋̀́̊͘͠ ̧̡͖͔͙͇͕͎̰̘̌͒̅̀ͫ̏̎́ͦ̅̓̕͠ą̛͕̟͓̪͉ͦ̋̈́ͬ̂̏̉̈ͥ̽̓̇ͩ͗̀̚r̴͉͍̮͎̪̩̖ͭ̋͆ͨͬ͂͒̽̂́͠ä̢̱͈͍̠̺̩̪̩̳̖̲̳͈́ͧͫͦ̆ͨͬͮ̉͋ͮ͋̌b̵̘̤̩̘̙̟̟̬͉̹̒ͯ͋ͤ̈͆͒͌ͬͥͣ̽ͩ͋̃͌ͬ̀́͞ṡ̶͑̓ͮ͏̮͕͙̘̺ķ̮͍̱̺͕̙͔͔̩͍̥̗͓̝̮̝̬́͌̃̎́ͫ̏̂̌ͬ̒̇̽͊̔̎ͦͪ͌͢͟͝i̴̢̮̘̪͕̖̦̯̘̗͚̣̮̳̰̠̯͉̰̋̍̂̀̊̋́ͯ͋̓ͬ͒͒ͦ͑̐̎̀͘͡m̡̡̬̜̠̬̦̹̻͍͓̜̰̺͗̎̐ͩḭ̡̡̹̳̱͙̱̠̬̌̇̿͊̋̉͒ͦ̔̏͟͝ ̶̨̨̝͖͕̜̦̥̤͇̥͙͙̜͎̗̲̞͎̯͒͒ͣͬ͂̉͂̈́́̐̓͛̊̃̂́͠ẓ̡̨̨̟̮͕̺̗̱̙͕̝̯͇̼͎͈͉͚̠̠̓̾ͥ́́͊͠͝ǹ̘̻͎̦̣ͣͪ̇̉ͨ̆͑̓͜͡ͅả̸̵͎̺̼̤̣̬͕̤̯̩͍̜͎̯ͫ̒ͦͪ̐̌ͤ͑̑̏͘͝c̷̈́̓ͫ̾͂҉̵̸̪̖͓̰͍̞͖̪̲̩̯̹̖͉̹z̛̭͙͓̜̯̱͉̹̝͉͎̙̻ͭͩ̄́͗͒͌ͭ̕͢k̢̛̘̦̟̩͆ͥ̀͊ͦ́ͯ͊͂͂ͧͬ̿̄ͣ́̍ͩ̀̚̕͞ạ̧̨̢̨̜̱͔̦̉̏ͦͮ̆̋͋̋̈̇̈́̃̑m̶̲͈͔͖͇̟͇̩̩͕̦̙̟̖͔̬ͣ͒̇̈̄͛̓ͩ̐̋ͩ̊̒̑̚͞ͅį͕̬̪͈̜̰̭͚̞̞̪̞͖͉̺̪̳͓̥̂ͯ̋̒ͫ͐͗͑͊̀́͞

**Comment by losek1** [comment]
m̷̲̣͚̎̆͆̽̃̌͊̅̅̐͆̉̀ͤ͋͐͠ͅa̯̦̬̙̞̞̤̙͎̳̜̮̲͓͎̣̹̓̋̈̍̓̓̎̆̈́̅͒̐ͮ́ͬ̒̾̏͝͝m̵̺̗͚̫̯̻͚͕̫̙̤͎̥͎̖̯̥͔̼̅ͣ̓́ͭͧ̑ͧ̎̏̋̄ͩ͗̓̒̕ ̷̷͉̼͙̰̟̼͌ͩ́̽̏̂ͥ̆̓ͨ̉̀̈́̊̄ͣ̑ͭ̃͡n̷̰̭͎͔͓͎̣̲̙̣ͯ̒͋̄ͬ̾ͣͩ̌̅ͬͤͣ̐́͠ͅä̷͙̥̠̻̠̗̪̅̀͒̋̈ͦͤ̆̑̃̔́̽̌ͭ̆ͤ͂̀ͅd̋̾ͪͤ̏̄̾ͥ̒̇ͨͣ̇̀̿́̎̓͗͏̸̧͏͔͕̘̘̻̣zͪ̆ͮͫ̌̐҉̧̥̖̮̮̤͔͕̥̤̰̲̲̞̮̰͓͜͡ͅi͕̤̪̘̳̹̭͛ͥͦ̐ͥ̽̇̑ͨ͡͞ē̘͖̝̳̱̰̭̘̲̮̭̓͑̏̄̑ͩ͌̌́́j̧̧ͩͦ̈́ͫͭͭ̾̈́ͫ̈̐͒ͬ͜͟͏̩̹̳̹͙͈̘͈͎̞̥̻̜͙̬͙ͅęͯͬ͂ͪ͆͒ͧ̔͆҉̵͓̣͔̦͔̤͖̱̗̞̺̻͎̗̠͔͞ͅͅ ̵̨̢͓̰͉̗̙̺̬͍͈͍̗̣̱̣͂̆͌͆͑͘ż̢̢͍̱͖̲̙̰̫͓͇͙̬̟̩͔̠̏͂͂̀ͥͮ̓͑͗̐̈́̒̆̐ͬ̍͂ͤ̚͝ê͗͌̆́̾͂ͦ̈͞͏͙͖͕̪̩͚͖̻̤̲͇͓ ̛̖̣͉̙͉͈̯͚̥̭̣͈̣̫̰̥͖͔̝̇̌̍͋̃̕̕p̤͚̮͓̜̳͙̬̼̰͉̻̯̠ͥͩͯ̃ͦͯ̚͘͠ơ̭̦̘̻̦̞̲̪̰͉̍̌̍̐̄ͦͮͫ͊̒̌́͡͝ͅͅm̙͚̝͔̠̘̯͙̦͍̭̉ͭ̃͐̆̿͐̓̀̚͝ơ̧̰̦̦͕͉̜̗̩͔͎̠̘̙̩͉͔̲̹̲̓ͣ̀̅̃̃ͦ̃ͤ̀̒̆͑͗͂͡g̴̶ͬ͛ͮ́̐ͯ̇ͤ̈́̐̑̃̍͆̾͑̉̚͏̵͖͔͍̲͎͍͎̙̤͖̹̱͎̻͟łͯ̅̒̎̍͗̒͢͏̸̪̠̝̬̭̜̝̱͔̞̪e̷͎͓͉̩͍̪̫͚̖̺̻̭̼̟̩͉̜̔ͨͥ͊ͧ̊̏ͫ̽͌̊͛̎ͪ̌̕m̸̷̝̩͓̠̪̙̱̺̲͎̩̝̬͇̹͇ͯ̅͂̋ͧ̾͒ͪ̂̽̽̄̾ͩ̏̈͟ ̴̴̴̡͎͕͙͙̯̯̞̼̠͍ͯͭ̂ͧ̉̀̀̍͡
