### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [losek1/Sounder#4]
hi @losek1 hi @hANSIc99 I contribute to open source softwares by designing logos.  I think this repo has no original logo. Have an my original logo idea.

Would you like to see this?

**Comment by losek1** [comment]
sure

**Comment by reallinfo** [comment]
Here you are. What do you think?

![sounder](https://user-images.githubusercontent.com/36298335/55294099-da9fb900-5423-11e9-97b8-a9f836be3a6b.jpg)

**Comment by losek1** [comment]
Brilliant job!

**Comment by losek1** [comment]
https://github.com/losek1/Sounder/invitations

**Comment by reallinfo** [comment]
Thanks! Do you have any color request?

**Comment by losek1** [comment]
Can you use black?

**Comment by reallinfo** [comment]
as you wish. If you don't have any other request, I'll send a pr.

**Comment by losek1** [comment]
Ok

**Comment by losek1** [comment]
I've added you as the collaborator.

**Comment by losek1** [comment]
When you are done working on logo drop it in the images folder.
Thanks again.

**Comment by reallinfo** [comment]
I've made the logo font more compatible with logomark. I also added the logo to the readme file.  Feel free to contact me if you need any other logo. Good works!

**Comment by losek1** [comment]
I've updated sounder icons.
Awesome work. <3
